import { FormEvent, useMemo, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { api } from "../api";

export default function ResetPassword() {
  const [params] = useSearchParams(); const token = useMemo(() => params.get("token") || "", [params]);
  const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [visible, setVisible] = useState(false);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const nav = useNavigate();
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); setMessage(""); if (password.length < 12) return setError("Use at least 12 characters."); if (password !== confirm) return setError("Passwords do not match."); setBusy(true); try { const result = await api<{ message: string }>("/auth/reset-password", { method: "POST", body: JSON.stringify({ token, password }) }); setMessage(result.message); setTimeout(() => nav("/admin/login"), 1800); } catch (err: any) { setError(err.message || "This reset link is invalid or expired."); } finally { setBusy(false); } };
  return <main className="auth-page"><div className="auth-shell"><Link className="auth-back" to="/admin/login">← Back to sign in</Link><section className="auth-card"><img className="auth-logo" src="/etef-logo.jpg" alt="ETEF logo" /><span className="eyebrow">SECURE PASSWORD RESET</span><h1>Set a new password</h1><p>Your new password must contain at least 12 characters.</p><form onSubmit={submit}><label className="admin-field"><span>New password</span><div className="password-wrap"><input type={visible ? "text" : "password"} autoComplete="new-password" value={password} onChange={e => setPassword(e.target.value)} required /><button type="button" className="password-toggle" onClick={() => setVisible(v => !v)} aria-label={visible ? "Hide password" : "Show password"}>{visible ? "◉" : "◌"}</button></div></label><label className="admin-field"><span>Confirm password</span><input type={visible ? "text" : "password"} autoComplete="new-password" value={confirm} onChange={e => setConfirm(e.target.value)} required /></label>{error && <div className="auth-error">{error}</div>}{message && <div className="auth-success">{message}</div>}<button className="button button-dark auth-submit" disabled={busy || !token}>{busy ? "Updating…" : "Reset password →"}</button></form></section></div></main>;
}
